goal_e_project/goal_e/urls.py
from django.urls import path
from . import views

app_name = 'goal_e'
urlpatterns = [
    path('', views.index, name='index'),
    path('pastGoals', views.past_goals, name='past_goals'),
    path('newGoal', views.new_goal, name='new_goal'),
    path('goals/<int:goal_id>', views.edit_goal, name='edit_goal'),
    path('deleteGoal', views.delete_goal, name='delete_goal'),
    path('goals/<int:goal_id>/complete', views.complete_goal, name='complete_goal'),
    path('signup', views.signup_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('signOut', views.sign_out_view, name='sign_out'),
    path('calendar/<int:month>/<int:year>', views.calendar_view, name='calendar'),
    path('calendar', views.calendar_view, name='calendar_default'),
    path('dailyGoals/<int:month>/<int:day>/<int:year>', views.daily_goals, name='daily_goals'),
    path('accountSettings', views.account_settings, name='account_settings'),
    path('usernameAvailable', views.username_available, name='username_available')
]

goal_e_project/goal_e_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('__admin__/', admin.site.urls),
    path('', include('goal_e.urls'))
]

handler404 = 'goal_e.views.resource_not_found'

goal_e_project/goal_e/models.py
# Model classes that map to the app's database via Django's ORM

from datetime import date

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

from .utils import get_full_date, days_before, num_str_with_commas

class Profile(models.Model):
    """User profile model class that extends built-in User model"""

    THEME_CHOICES = [
        (1, 'Light'),
        (2, 'Dark')
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    theme = models.IntegerField(choices=THEME_CHOICES, default=1)

    def add_points(self, points, save=True):
        self.points += points

        if self.points < 0:
            self.points = 0

        if save:
            self.save()

    def get_points_str(self):
        return num_str_with_commas(self.points)

    def __str__(self):
        return f"{self.user.username}'s profile"

class Goal(models.Model):
    """Goal model class"""

    PRIORITY_CHOICES = [
        (1, 'Low'),
        (2, 'Medium'),
        (3, 'High')
    ]

    PROGRESS_VALIDATORS = [MinValueValidator(0.0), MaxValueValidator(100.0)]

    title = models.CharField(max_length=65)
    description = models.TextField(null=True, blank=True)
    deadline = models.DateField()
    progress = models.FloatField(default=0.0, validators=PROGRESS_VALIDATORS)
    priority = models.IntegerField(choices=PRIORITY_CHOICES, default=2)
    completed = models.DateField(null=True, blank=True)

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def get_progress_str(self):
        if self.progress % 1 == 0:
            return f'{int(self.progress)}%'
        
        return f'{self.progress:.2f}%'
    
    def get_deadline_str(self):
        return get_full_date(self.deadline)
    
    def get_completed_str(self):
        if self.completed:
            return get_full_date(self.completed)
        
    def get_title_str(self):
        str_len = 30
        title_str = self.title[:str_len]

        if len(self.title) > str_len:
            title_str += '...'

        return title_str
    
    def calculate_points(self):
        points = 0
        
        if self.completed:
            base = 10000
            days_before_deadline = days_before(self.completed, self.deadline)
            mult = 1000

            if days_before_deadline > 0:
                days_bonus = min(mult * days_before_deadline, 10000)
            else: 
                days_bonus = 0
            
            points = (base + days_bonus) * self.priority

        return points
        
    def add_points(self):
        points = self.calculate_points()
        self.profile.add_points(points)

        return points
    
    def undo_points(self, points=None):
        points = points or self.calculate_points()
        self.profile.add_points(-points)

        return points
    
    def complete_goal(self):
        self.completed = date.today()
        self.progress = 100.0
        
        points = self.add_points()
        return points

    def undo_complete(self, points=None):
        points = self.undo_points(points)
        self.completed = None
        
        return points

    def __str__(self):
        return self.title

goal_e_project/goal_e/views.py
# View functions for handling server requests / responses

from datetime import date
from json import loads

from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpRequest, HttpResponseRedirect, JsonResponse, Http404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import Goal, Profile
from .goal_calendar import GoalCalendar, GoalCalendarNode

from .utils import (
    prepare_goal_params, 
    get_yyyy_mm_dd, 
    get_week_from_today_str, 
    add_years, 
    num_str_with_commas,
    get_prev_action,
    redirect_when_logged_in,
    get_user_errors,
    get_full_date,
    previous_url,
    get_prev_url,
    url_equals_reversed,
    get_next_month_year,
    get_prev_month_year,
    get_month_input_val,
    user_already_exists,
    valid_username
)

@login_required
def index(request: HttpRequest):
    profile = request.user.profile
    goal_list = Goal.objects.filter(profile=profile, completed=None).order_by('deadline', '-priority')

    context = {
        'title': 'Current Goals',
        'goal_list': goal_list,
        'prev_action': get_prev_action(request)
    }

    return render(request, 'goal_e/index.html', context)

@login_required
def past_goals(request: HttpRequest):
    profile = request.user.profile
    goal_list = Goal.objects.filter(profile=profile).exclude(completed=None).order_by('-completed', '-priority')

    context = {
        'title': 'Past Goals',
        'goal_list': goal_list,
        'prev_action': get_prev_action(request)
    }

    return render(request, 'goal_e/index.html', context)

@login_required
def new_goal(request: HttpRequest):
    if request.method == 'POST':
        [title, description, deadline, priority, progress] = prepare_goal_params(request)
        profile = request.user.profile

        goal = Goal(title=title, 
                    description=description, 
                    deadline=deadline, 
                    priority=priority, 
                    progress=progress,
                    profile=profile)
        
        goal.full_clean()
        if goal.progress == 100.0:
            goal.complete_goal()
            
        goal.save()
        request.session['prev_action'] = ('Goal Set!', 'blue')
        return HttpResponseRedirect(reverse('goal_e:index'))

    context = { 
        'default_date': get_week_from_today_str(),
        'min_date': get_yyyy_mm_dd(date.today()),
        'max_date': get_yyyy_mm_dd(add_years(date.today(), 100)),
        'prev_url': get_prev_url(request, False)
        }
   
    return render(request, 'goal_e/new_goal.html', context)

@login_required
def edit_goal(request: HttpRequest, goal_id: int):
    profile = request.user.profile
    goal = get_object_or_404(Goal, id=goal_id, profile=profile)

    if request.method == 'POST':
        [title, description, deadline, priority, progress] = prepare_goal_params(request)
        prev_points = goal.calculate_points()

        goal.title = title
        goal.description = description
        goal.deadline = deadline
        goal.priority = priority
        goal.progress = progress

        goal.full_clean()

        completion_undone = False
        if (goal.progress == 100.0) and (not goal.completed):
            goal.complete_goal()
        elif goal.completed and (goal.progress < 100.0):
            goal.undo_complete(prev_points)
            completion_undone = True
        
        goal.save()
        
        prev_url = get_prev_url(request)
        if goal.completed and url_equals_reversed(prev_url, 'goal_e:index'):
            response = HttpResponseRedirect(reverse('goal_e:past_goals') + f'#{goal.id}')
        elif completion_undone and url_equals_reversed(prev_url, 'goal_e:past_goals'):
            response = HttpResponseRedirect(reverse('goal_e:index') + f'#{goal.id}')
        else:
            response = HttpResponseRedirect(prev_url + f'#{goal.id}')

        return response

    today = date.today()
    min_date = min(goal.deadline, today)
    
    context = {
        'goal': goal,
        'date_val': get_yyyy_mm_dd(goal.deadline),
        'min_date': get_yyyy_mm_dd(min_date),
        'max_date': get_yyyy_mm_dd(add_years(today, 100))
    }

    request.session['prev_url'] = previous_url(request)
    return render(request, 'goal_e/edit_goal.html', context)

@login_required
def delete_goal(request: HttpRequest):
    if request.method == 'POST':
        goal_id = request.POST['id']
        profile = request.user.profile
        
        goal = get_object_or_404(Goal, id=goal_id, profile=profile)
        goal.delete()

        request.session['prev_action'] = ('Goal Deleted', 'red')

    return HttpResponseRedirect(get_prev_url(request))

@login_required
def complete_goal(request: HttpRequest, goal_id: int):
    response = {'error': 'operation unsuccessful'}

    if request.method == 'POST':
        profile = request.user.profile
        goal = get_object_or_404(Goal, id=goal_id, profile=profile)

        points = goal.complete_goal()
        goal.save()

        response = {
            'pointsAdded': num_str_with_commas(points),
            'newPointsTotal': goal.profile.get_points_str(),
            'dateStr': goal.get_completed_str(),
            'title': goal.get_title_str()
        }

    return JsonResponse(response)

@login_required
def resource_not_found(request: HttpRequest, exception=None):
    if 'goals' in request.path:
        title = 'Goal Not Found'
    else:
        title = '404: Page Not Found'

    response = render(request, 'goal_e/not_found.html', { 'title': title })
    response.status_code = 404

    return response 

@redirect_when_logged_in
def signup_view(request: HttpRequest):
    context = {}
    status_code = 200

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password_conf = request.POST['confirmPassword']

        errors = get_user_errors(username, password, password_conf)

        if not errors:
            user = User.objects.create_user(username, password=password)
            profile = Profile.objects.create(user=user)

            login(request, user)
            return HttpResponseRedirect(reverse('goal_e:index'))
        else:
            context = {
                'username': username,
                'errors': errors
            }

            status_code = 400

    response = render(request, 'auth/signup.html', context)
    response.status_code = status_code

    return response

@redirect_when_logged_in
def login_view(request: HttpRequest):
    context = {}
    status_code = 200

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)

            return HttpResponseRedirect(reverse('goal_e:index'))
        else:
            context = {
                'username': username,
                'message': 'Invalid username and/or password'
            }

            status_code = 401 
    
    response = render(request, 'auth/login.html', context)
    response.status_code = status_code
    
    return response

@login_required
def sign_out_view(request: HttpRequest):
    logout(request)

    return HttpResponseRedirect(reverse('goal_e:login'))

@login_required
def calendar_view(request: HttpRequest, month: int = None, year: int = None):
    profile = request.user.profile
    today = date.today()

    if not (month or year):
        month = today.month
        year = today.year

    date_plus_100 = add_years(today, 100)
    max_date = get_month_input_val(date_plus_100.month, date_plus_100.year)

    today_id = None
    if month == today.month and year == today.year:
        today_id = f'True{today.day}'

    context = {
        'month_input_val': get_month_input_val(month, year),
        'calendar': GoalCalendar(month, year, profile, GoalCalendarNode).data,
        'next': get_next_month_year(month, year),
        'prev': get_prev_month_year(month, year),
        'month': month,
        'year': year,
        'max_date': max_date,
        'today_id': today_id
    }

    return render(request, 'goal_e/calendar.html', context)

@login_required
def daily_goals(request: HttpRequest, month: int, day: int, year: int):
    profile = request.user.profile
    day_date = date(year, month, day)
    goal_list = Goal.objects.filter(profile=profile, deadline=day_date).order_by('completed', '-priority')

    context = {
        'title': f'Goals for {get_full_date(day_date)}',
        'goal_list': goal_list,
        'prev_action': get_prev_action(request),
        'month': month,
        'year': year
    }

    return render(request, 'goal_e/index.html', context)

@login_required
def account_settings(request: HttpRequest):
    user = request.user
    profile = user.profile
    
    status_code = 200
    errors = None
    
    if request.method == 'POST':
        new_username = request.POST['username']
        new_pword = request.POST['password']
        new_pword_conf = request.POST['confirmPassword']
        new_theme = request.POST['theme']

        errors = get_user_errors(new_username, new_pword, new_pword_conf, user)

        if not errors:
            if user.username != new_username:
                user.username = new_username

            if new_pword:
                user.set_password(new_pword)

            if new_theme != profile.theme:
                profile.theme = new_theme

            profile.full_clean()
            user.save()
            profile.save()
            
            login(request, user)
            request.session['prev_action'] = ('Settings Saved', 'blue')
        else:
            request.session['prev_action'] = ('Error Saving Settings', 'red')

goal_e_project/goal_e/templates/goal_e/acnt_settings.html
{% extends 'base.html' %}

{% load static %}

{% block css/js %}
    <script src="{% static 'goal_e/js/acntSettings.js' %}"></script>
    <script src="{% static 'goal_e/js/utils.js' %}"></script>
{% endblock %}

{% block main %}
    <h1 class="pageTitle" id="acntSettingsTitle">Account Settings</h1>

    <!-- Account Settings Form -->
    <form method="post" class="blue" id="acntSettingsForm" onsubmit="validatePasswords(event, 'invalidMsgAcnt')">
        {% csrf_token %}

        <div class="formEle">
            <label for="username">Username</label>
            
            <div id="usernameContainer">
                <input type="text" id="username" name="username" value="{{ user }}" oninput="removeAvailableInfo()" maxlength="30" autocomplete="off" required>
                <div id="checkAvail" onclick="checkUsernameAvailable('invalidMsgAcnt')">Available?</div>
            </div>
        </div>

        <div id="passwordsContainer">
            <div class="formEle">
                <label for="password">New Password</label>
                <input type="password" id="password" name="password" placeholder="Leave blank for no change" autocomplete="new-password">
            </div>

            <div class="formEle">
                <label for="confirmPassword">Confirm New Password</label>
                <input type="password" id="confirmPassword" name="confirmPassword" placeholder="Leave blank for no change" autocomplete="new-password">
            </div>
        </div>

        <div class="formEle">
            <label>Theme</label>
            <div id="themeBtns">
                <button type="button" onclick="changeTheme(this, 1)" id="themeBtn1" {% if profile.theme == 1 %} class="selected" {% endif %} aria-controls="theme">Light</button>
                <button type="button" onclick="changeTheme(this, 2)" id="themeBtn2" {% if profile.theme == 2 %} class="selected" {% endif %} aria-controls="theme">Dark</button>
            </div>

            <input type="hidden" id="theme" name="theme" value="{{ profile.theme }}">
        </div>

        <button type="submit">Save Settings</button>
    </form>

    <a id="cancelBtn" href="{% url 'goal_e:index' %}">Cancel</a>

    {% if errors %}
        
    <div id="invalidMsgAcnt">
        {% if errors.user %}
            <p>{{ errors.user.0 }}</p>
        {% endif %}

        {% if errors.password %}
            <p>{{ errors.password.0 }}</p>
        {% endif %}    
    </div>

    {% endif %}

{% endblock %}

{% comment %} Remove add button {% endcomment %}
{% block bottom %}
{% endblock %}

goal_e_project/goal_e/templates/goal_e/calendar.html
{% extends 'base.html' %}

{% load static %}

{% block css/js %}
    <script src="{% static 'goal_e/js/calendar.js' %}"></script>
{% endblock %}

{% block main %}

    <div id="calendarTitle">
        <a id="left" href="{% url 'goal_e:calendar' prev.0 prev.1 %}"><i class="fa-solid fa-chevron-left fa-xl"></i></a>
        
        <input type="month" value="{{ month_input_val }}" id="monthInput" onchange="handleMonthChange('{% url 'goal_e:calendar_default' %}')" min="2023-01" max="{{ max_date }}" size="5"></input>  

        <a id="right" href="{% url 'goal_e:calendar' next.0 next.1 %}"><i class="fa-solid fa-chevron-right fa-xl"></i></a>
    </div>

    <!-- Monthly Calendar -->
    <table class="calendar">
        <thead>
            <tr>
                <th>Mon</th>
                <th>Tue</th>
                <th>Wed</th>
                <th>Thu</th>
                <th>Fri</th>
                <th>Sat</th>
                <th>Sun</th>
            </tr>
        </thead>

        <tbody>
        {% for week in calendar %}
            
            <tr>
            {% for node in week %}
            
                <td class="{{ node.current_month }}" id="{{ node.current_month }}{{ node.day }}">
                    {{ node.day }}
                    
                    {% if node.goals %}
                        <a class="calendarStar {{ node.get_css_class }}" href="{% url 'goal_e:daily_goals' month node.day year %}">
                            <i class="fa-solid {{ node.get_icon_class }} icon-larger"></i>
                        </a>
                    {% endif %}
                </td>

            {% endfor %}
            </tr>

        {% endfor %}
        </tbody>
    </table>

    {% if today_id %}
        <!-- Apply class for current day -->
        <script>
            applyTodayClass("{{ today_id }}")
        </script>
    {% endif %}

{% endblock %}

goal_e_project/goal_e/templates/goal_e/edit_goal.html
{% extends 'base.html' %}

{% load static %}

{% block css/js %}
    <script src="{% static 'goal_e/js/goalForms.js' %}"></script>
    <script src="{% static 'goal_e/js/utils.js' %}"></script>
{% endblock %}

{% block main %}
    <h1 class="pageTitle">Edit Goal</h1>

    <!-- Edit Goal Form -->
    <form method="post" class="{{goal.get_priority_display}}" id="goalForm">
        {% csrf_token %}

        <div class="formEle">
            <label for="title">Title</label>
            <input type="text" id="title" name="title" maxlength="65" placeholder="Read 100 books, walk 1000 steps, etc." value="{{ goal.title }}" required>
        </div>

        <div class="formEle">
            <label for="description">Description (Optional)</label>
            <textarea id="description" name="description" rows="5" maxlength="750" placeholder="I want to complete this goal because...">{{ goal.description }}</textarea>
        </div>

        <div class="formEle">
            <label for="deadline">Deadline</label>
            <input type="date" id="deadline" name="deadline" value="{{ date_val }}" min="{{ min_date }}" max="{{ max_date }}" required>
        </div>

        <div class="formEle">
            <label>Priority</label>
            <div id="priorityBtns">
                <button type="button" onclick="setPriority(1)" id="lowBtn" {% if goal.priority == 1 %} class="selected" {% endif %} >Low</button>
                <button type="button" onclick="setPriority(2)" id="medBtn" {% if goal.priority == 2 %} class="selected" {% endif %}>Medium</button>
                <button type="button" onclick="setPriority(3)" id="highBtn" {% if goal.priority == 3 %} class="selected" {% endif %}>High</button>
            </div>

            <input type="hidden" id="priority" name="priority" value="{{ goal.priority }}">
        </div>

        <div class="formEle">
            <div id="progHeader">
                <label for="progress">Progress</label>

                <span>
                    <input type="number" id="progress" name="progress" value="{{ goal.progress }}" min="0" max="100" step="any" onchange="changeProgBar()" aria-controls="progressBar" required>
                    %
                </span>
            </div>
            
            <input type="range" value="{{ goal.progress }}" min="0" max="100" id="progressBar" oninput="changeProgInput()" aria-controls="progress">
        </div>

        <button type="submit">Update Goal!</button>
    </form>

    <a id="cancelBtn" onclick="showElementOverlay('deleteBox')">Delete</a>

    <!-- Delete Confirmation Box -->
    <form action="{% url 'goal_e:delete_goal'%}" method="post" id="deleteBox" class="hide">
        {% csrf_token %}
        
        <p>Are you sure you want to delete this goal?</p>

        <div id="deleteFormBtns">
            <button type="button" id="cancelDelete" onclick="hideElementOverlay('deleteBox')">No, Cancel</button>
            <button type="submit" id="deleteConfirm">Yes, Confirm Delete</button>
        </div>

        <input type="hidden" value="{{ goal.id }}" name="id" id="goalID">
    </form>

{% endblock %}

{% comment %} Remove add button {% endcomment %}
{% block bottom %}
{% endblock %}

goal_e_project/goal_e/templates/goal_e/index.html
{% extends 'base.html' %}

{% load static %}

{% block css/js %}
    <script src="{% static 'goal_e/js/utils.js' %}"></script>
{% endblock %}

{% block main %}

    <h1 class="pageTitle" {% if month %} id="dailyTitle" {% endif %}>{{ title }}</h1>

    {% if goal_list|length == 0 %}

        {% if title == 'Current Goals' %}
            <div id="noElesMsg">
                <p>There are no goals yet!</p>
                <a href="{% url 'goal_e:new_goal' %}">Add one now</a>
            </div>
        {% else %}
            <div id="noElesMsg">
                <p>None yet!</p>
                <a href="{% url 'goal_e:index' %}">Check current goals</a>
            </div>
        {% endif %}

    {% else %}
        
        {% csrf_token %}
        
        <!-- Goal List -->
        <div id="goalList">
        {% for goal in goal_list %}
            
            <div class="goalCard {{goal.get_priority_display}}" id="{{ goal.id }}">
                <h2>{{ goal.title }}</h2>
                
                <a class="editLink" href="{% url 'goal_e:edit_goal' goal.id %}">
                    <i class="fa-solid fa-pen-to-square"></i>
                </a>
                
                {% if goal.description %}
                    <div class="descript">{{ goal.description }}</div>
                {% endif %}

                <div class="deadline">Deadline: <span>{{ goal.get_deadline_str }}</span></div>
                <div class="priority">{{ goal.get_priority_display }} Priority</div>
                
                <div class="prog">
                    <p>Progress</p>

                    <div class="progBar">
                        <div class="bar" style="width:{{ goal.progress }}%"></div>
                        <p>{{ goal.get_progress_str }}</p>
                    </div>
                </div>

                {% if goal.completed %}
                    <button class="completeBtn completedMsg" id="completeBtn{{ goal.id }}" type="button">Completed on {{ goal.get_completed_str }}!</button>
                {% else %}
                    <button class="completeBtn" id="completeBtn{{ goal.id }}" type="button" onclick="markGoalComplete({{ goal.id }})">Mark as complete!</button>
                {% endif %}
            </div>
        
        {% endfor %}
        </div>
        
        <!-- Mark Goal as Complete Pop-up -->
        <div id="completedPopUp" class="hide">
            <p id="upperPopUp">
                Congratulations on completing the goal: <span class="popUpTitle"></span>!
                You have earned <span class="popUpPoints"></span> points!</p>
            </p>

            <p id="lowerPopUp">Click anywhere to continue</p>
        </div>

        {% if goal_list|length > 1 %}
            <!-- Extra Space for Add Goal Button -->
            <br><br>   
        {% endif %}
    
    {% endif %}

    {% if month %}
        <a class="calendarLink" href="{% url 'goal_e:calendar' month year %}">Back to calendar</a>
    {% endif %}
        
{% endblock %}

goal_e_project/goal_e/templates/goal_e/new_goal.html
{% extends 'base.html' %}

{% load static %}

{% block css/js %}
    <script src="{% static 'goal_e/js/goalForms.js' %}"></script>
{% endblock %}

{% block main %}
    <h1 class="pageTitle">New Goal</h1>

    <!-- New Goal Form -->
    <form method="post" class="Medium" id="goalForm">
        {% csrf_token %}

        <div class="formEle">
            <label for="title">Title</label>
            <input type="text" id="title" name="title" maxlength="65" placeholder="Read 100 books, walk 1000 steps, etc." required>
        </div>

        <div class="formEle">
            <label for="description">Description (Optional)</label>
            <textarea id="description" name="description" rows="5" maxlength="750" placeholder="I want to complete this goal because..."></textarea>
        </div>

        <div class="formEle">
            <label for="deadline">Deadline</label>
            <input type="date" id="deadline" name="deadline" value={{ default_date }} min="{{ min_date }}" max="{{ max_date }}" required>
        </div>

        <div class="formEle">
            <label>Priority</label>
            <div id="priorityBtns">
                <button type="button" onclick="setPriority(1)" id="lowBtn" aria-controls="priority">Low</button>
                <button type="button" onclick="setPriority(2)" id="medBtn" class="selected" aria-controls="priority">Medium</button>
                <button type="button" onclick="setPriority(3)" id="highBtn" aria-controls="priority">High</button>
            </div>

            <input type="hidden" id="priority" name="priority" value="2">
        </div>

        <div class="formEle">
            <div id="progHeader">
                <label for="progress">Progress</label>

                <span>
                    <input type="number" id="progress" name="progress" value="0" min="0" max="100" step="any" onchange="changeProgBar()" aria-controls="progressBar" required>
                    %
                </span>
            </div>
            
            <input type="range" value="0" min="0" max="100" id="progressBar" oninput="changeProgInput()" aria-controls="progress">
        </div>

        <button type="submit">Set Goal!</button>
    </form>

    <a id="cancelBtn" href="{{ prev_url }}">Cancel</a>

{% endblock %}

{% comment %} Remove add button {% endcomment %}
{% block bottom %}
{% endblock %}

goal_e_project/goal_e/templates/goal_e/not_found.html
{% extends 'base.html' %}

{% block main %}
    <h1 class="pageTitle">{{ title }}</h1>

    <a id="notFoundLink" href="{% url 'goal_e:index' %}">Return to current goals</a>
{% endblock %}